plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

release:
  branches:
    - main
    - dev/*

branches:
  - main
  - name: dev/*
    prerelease: true
  - name: feature/*
    prerelease: true
  - name: hotfix/*
    prerelease: true
