services:
    db:
        image: postgres:16.9-alpine
        container_name: db
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
    back:
        image: "monitoverse-back:latest"
        restart: always
        depends_on:
            - db
        container_name: back
        ports:
            - "8081:8081"
        volumes:
            - ./back:/app
            - /var/run/docker.sock:/var/run/docker.sock
        command: air
        environment:
            - JWT_SECRET=${JWT_SECRET}
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_PORT=${BACK_DB_PORT}
    front:
        image: "monitoverse-front:latest"
        container_name: front
        volumes:
            - ./front:/app
        ports:
            - 5173:5173
        command: bun run dev
