services:
    db:
        image: postgres:16.9-alpine
        container_name: db
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
    back:
        image: "back"
        restart: always
        depends_on:
            - db
        container_name: back
        ports:
            - "8081:8081"
        volumes:
            - ./back:/app
            - /var/run/docker.sock:/var/run/docker.sock
        build:
            context: ./back
            dockerfile: dockerfile.dev
        command: air
    front:
        image: "front"
        container_name: front
        build:
            context: ./front
            dockerfile: dockerfile
        volumes:
            - ./front:/app
        ports:
            - 5173:5173
        command: bun run dev
