# .air.toml
root = "."
tmp_dir = "tmp"

[build]
# commande pour builder
cmd = "go build -o tmp/main ."
# binaire à relancer
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "node_modules"]
# délai avant rebuild (en ms)
delay = 100

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
