name: CI Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  go:
    name: Go Lint → Build → Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: back

      - name: Build
        run: |
          cd back
          go build ./...

      - name: Test
        run: |
          cd back
          go test ./...

  react:
    name: React (Bun) Lint → Build → Test
    runs-on: ubuntu-latest
    needs: go
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Bun
        uses: jarred-sumner/bun-action@v1
        with:
          version: "1.x"

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/deps
            ~/.cache/bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies
        run: bun install

      - name: Run Lint
        run: bun lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun test
