name: Release

on:
  workflow_call:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git user
        run: |
          git config --global user.email "release-bot@example.com"
          git config --global user.name "Release Bot"
      - name: 🚀 Run release-it
        run: pnpx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.monitoverse }}
